[package]
name = "bevy-me-website"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.1", default-features = false, features = [
    "default_app",
    "3d_bevy_render",
    "scene",
    "picking",
    "std",
    "bevy_winit",
    "bevy_clipboard",
    "default_font",
    "webgl2",
    "x11",
    "custom_cursor",
    "sysinfo_plugin",
] }
